# Generated by Django 4.2.6 on 2023-11-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=850)),
                ('images', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='images',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
