# Generated by Django 4.2.6 on 2023-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_testimonial_alter_package_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=850)),
                ('images', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='testimonial',
        ),
    ]
