# Generated by Django 4.2.6 on 2023-11-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_contact_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='uploads/')),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
