# Generated by Django 4.2.6 on 2023-11-16 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_events_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=20)),
                ('night', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=2000)),
                ('destination1', models.CharField(max_length=20)),
                ('destination2', models.CharField(max_length=20)),
                ('destination3', models.CharField(max_length=20)),
                ('destination_des1', models.CharField(max_length=1000)),
                ('destination_des2', models.CharField(max_length=1000)),
                ('destination_des3', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('image1', models.ImageField(upload_to='uploads/')),
                ('image2', models.ImageField(upload_to='uploads/')),
                ('image3', models.ImageField(upload_to='uploads/')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.package')),
            ],
        ),
    ]
